Repository Luroyi/solars-port-android-java, pull requests merged in 2024-07, with the labels that each got.

#4 Recover password
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/solar_sport_android_java/RecuperarContrasenaActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/recuperar_contrasena.xml
Labels: enhancement

#6 recuperar contraseña
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/create_a_password.xml
  app/src/main/res/layout/recovery_pass.xml
  app/src/main/res/layout/validate_code.xml
Labels: enhancement

#7 Fix carrusel and navegation
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/solar_sport_android_java/CarouselAdapter.java
  app/src/main/java/com/example/solar_sport_android_java/DashboardActivity.java
  app/src/main/java/com/example/solar_sport_android_java/MainScreenActivity.java
  app/src/main/java/com/example/solar_sport_android_java/RecoveryPassActivity.java
  app/src/main/java/com/example/solar_sport_android_java/ValidateCodeActivity.java
  app/src/main/java/com/example/solar_sport_android_java/ui/theme/Color.kt
  app/src/main/java/com/example/solar_sport_android_java/ui/theme/Theme.kt
  app/src/main/java/com/example/solar_sport_android_java/ui/theme/Type.kt
  app/src/main/res/drawable/baseline_account_circle_24.xml
  app/src/main/res/drawable/imagen1.png
  app/src/main/res/drawable/imagen2.png
  app/src/main/res/drawable/imagen3.png
  app/src/main/res/drawable/imagen4.png
  app/src/main/res/drawable/imagen5.png
  app/src/main/res/drawable/imagen6.png
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/item_carousel.xml
  app/src/main/res/layout/main_screen.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/layout/recovery_pass.xml
  app/src/main/res/layout/validate_code.xml
  app/src/main/res/menu/menu_drawer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: documentation, enhancement

#9 pagina principal
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/solar_sport_android_java/DashboardActivity.java
  app/src/main/res/drawable/baseline_menu_24.xml
  app/src/main/res/drawable/button_background_rectangular.xml
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/create_a_password.xml
  app/src/main/res/layout/register_terrace.xml
  app/src/main/res/menu/top_app_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, wontfix

#10 pagina beneficios
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/solar_sport_android_java/DashboardActivity.java
  app/src/main/java/com/example/solar_sport_android_java/LoginActivity.java
  app/src/main/java/com/example/solar_sport_android_java/PopupWindowActivity.java
  app/src/main/java/com/example/solar_sport_android_java/ProductionStatisticsActivity.java
  app/src/main/java/com/example/solar_sport_android_java/RecoveryPassActivity.java
  app/src/main/java/com/example/solar_sport_android_java/RegisterActivity.java
  app/src/main/java/com/example/solar_sport_android_java/Registerterrace.java
  app/src/main/java/com/example/solar_sport_android_java/ResgistroExitosoActivity.java
  app/src/main/java/com/example/solar_sport_android_java/SolarEnergyBenefitsActivity.java
  app/src/main/java/com/example/solar_sport_android_java/TerraceCategoriesActivity.java
  app/src/main/res/drawable/ahorro_energia.png
  app/src/main/res/drawable/ampliacion_del_sistema.png
  app/src/main/res/drawable/baterias_almacenamiento.png
  app/src/main/res/drawable/energia_limpia_renovable.png
  app/src/main/res/drawable/estadio.png
  app/src/main/res/drawable/estadisticas.png
  app/src/main/res/drawable/incrementar_valor.png
  app/src/main/res/drawable/monitoreo_regular.png
  app/src/main/res/drawable/optimizar_energia.png
  app/src/main/res/drawable/paneles.png
  app/src/main/res/drawable/reduccion_huella_co2.png
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/popup_window.xml
  app/src/main/res/layout/production_statistics.xml
  app/src/main/res/layout/register_terrace.xml
  app/src/main/res/layout/resgistro_exitoso.xml
  app/src/main/res/layout/solar_energy_benefits.xml
  app/src/main/res/layout/terrace_categories.xml
  app/src/main/res/layout/validate_code.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: wontfix

#11 estadisticas
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/solar_sport_android_java/Registerterrace.java
  app/src/main/java/com/example/solar_sport_android_java/ResgistroExitosoActivity.java
  app/src/main/java/com/example/solar_sport_android_java/SolarEnergyBenefitsActivity.java
  app/src/main/res/drawable/registro_exitoso.png
  app/src/main/res/layout/popup_window.xml
  app/src/main/res/layout/resgistro_exitoso.xml
Labels: wontfix

#13 Fix boton vista popup
  app/src/main/java/com/example/solar_sport_android_java/CreatePasswordActivity.java
  app/src/main/java/com/example/solar_sport_android_java/DashboardActivity.java
  app/src/main/java/com/example/solar_sport_android_java/PopupWindowActivity.java
  app/src/main/java/com/example/solar_sport_android_java/Registerterrace.java
  app/src/main/java/com/example/solar_sport_android_java/TerraceCategoriesActivity.java
  app/src/main/res/layout/activity_dashboard.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/create_a_password.xml
  app/src/main/res/layout/popup_window.xml
  app/src/main/res/layout/production_statistics.xml
  app/src/main/res/layout/recovery_pass.xml
  app/src/main/res/layout/register_terrace.xml
  app/src/main/res/layout/terrace_categories.xml
  app/src/main/res/layout/validate_code.xml
Labels: wontfix

#14 Create README.md
  README.md
Labels: documentation
